name=EmbedDIP
version=alpha
author=Ozan Durgut
maintainer=Ozan Durgut <ozandurgut.2001@hotmail.com>
sentence=An embedded digital image processing library for Arduino and STM32.
paragraph=A modular C/C++ image processing library built for low-resource microcontrollers.
category=Signal Input/Output
url=https://github.com/EmbedDIP/embedDIP
architectures=*
includes=embedDIP.h